Update RegressionTest to assume UTF-8.
NationalSecurityAgency/emissary pull request #1006
Opened 2024-11-01 18:45 UTC by jdcove2

This PR updates RegressionTest to assume all byte arrays are UTF-8 and not process them as ASCII (i.e. ISO_8859_1). The main benefit of this is that valid UTF-8 is output in the XML directly instead of being hashed or BASE64'd.

NOTE: This is a potentially "breaking" change that might require XML files to be regenerated.

2024-11-07 15:43 UTC, dev-mlb requested changes

2024-11-07 15:43 UTC, dev-mlb commented on src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
> +    public static boolean requiresEncoding(final byte[] utf8Bytes) {
Any reason not to update the ByteUtil or add these methods to a util class?? Also, since these are public methods, I'd like to see some javadocs.

2024-11-15 17:42 UTC, fbruton requested changes

2024-11-15 17:42 UTC, fbruton commented on src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java
> +    public static boolean requiresEncoding(final byte[] utf8Bytes) {
Recommend removing `requiresEncoding` method and updating any calls to `requiresEncoding` to call ByteUtil#containsNonIndexableBytes instead.

2024-11-25 22:14 UTC, dev-mlb approved these changes

2024-11-26 12:56 UTC, ldhardy approved these changes

2024-12-05 15:18 UTC, merged