byteutil :: add support to check for non-indexable chars
NationalSecurityAgency/emissary pull request #1010
Opened 2024-11-13 22:07 UTC by dev-mlb

2024-11-14 20:55 UTC, fbruton requested changes

2024-11-14 20:55 UTC, fbruton commented on src/main/java/emissary/util/ByteUtil.java
> +            return false;
```suggestion
            return true;
```

2024-11-14 21:17 UTC, sambish5 approved these changes

2024-11-15 00:34 UTC, fbruton approved these changes

2024-11-15 02:53 UTC, merged