update maven-assembly-plugin to 3.7.1
NationalSecurityAgency/emissary pull request #1011
Opened 2024-11-14 15:58 UTC by dev-mlb

2024-11-15 14:56 UTC, sambish5 approved these changes

2024-11-15 15:05 UTC, jpdahlke commented
- [ ] validate versions are available internally

2024-11-15 15:46 UTC, cfkoehler reviewed
Not done checking yet.
Ran the following goals so far (compile, verify, site)

2024-11-15 15:46 UTC, cfkoehler commented on pom.xml
> +    <plugin.duplicate-finder-maven.version>2.0.1</plugin.duplicate-finder-maven.version>
not available yet

2024-11-15 15:46 UTC, cfkoehler commented on pom.xml
> +    <plugin.maven-surefire.version>3.5.2</plugin.maven-surefire.version>
not available yet. (surefire-junit-platform)
have 3.2.3

2024-11-15 15:46 UTC, cfkoehler commented on pom.xml
> +    <plugin.maven-site.version>3.21.0</plugin.maven-site.version>
not available yet

2024-12-18 15:46 UTC, jpdahlke requested changes
I was able to build these changes internally using this 'incremental' path of commands: 
```
mvn clean verify
mvn clean install
mvn clean verify -Pcheckstyle
mvn clean verify -Pcheckstyle,pmd,coverage
mvn clean site
mvn clean deploy (failed to connect to repo due to access but plugin worked)
mvn clean install site -Pcheckstyle,pmd,coverage
```
All of which 'worked' (success at the end) but I believe I could have just done the last command and been covered (except for deploy), it just would have been harder to find issues with missing dependencies.

I did run into an issue where the maven-project-info-reports had errors when using the cyclonedx plugin. I recommend bumping that to the latest 2.9.1 version as well as adding this plugin dependency to try to manage the version being used with cyclone (it uses 2.0.8 now):
```
<plugin>
  <groupId>io.takari.maven.plugins</groupId>
  <artifactId>takari-lifecycle-plugin</artifactId>
  <version>2.2.0</version>
</plugin>
```
I also see an error during pmd generating the CPD report for a NoSuchMethodError which complains about org.apache.maven.doxia.sink.Sink.verbatim(). I didn't investigate if that was new or where that might have started but it appears as though there are two versions of doxia being included, 2.0.0 and 1.11.1 using:
```
mvn dependency:resolve-plugins
```
Since the result is not a failure of the build but a failure of report generation I'm ok moving forward and resolving in a follow-up pending your feedback.

2024-12-19 17:09 UTC, jpdahlke commented on pom.xml
> +    <plugin.takari-lifecycle>2.2.0</plugin.takari-lifecycle>
```suggestion
    <plugin.takari-lifecycle>2.0.8</plugin.takari-lifecycle>
```

2024-12-19 17:10 UTC, jpdahlke approved these changes

2024-12-19 17:50 UTC, jpdahlke commented
`mvn clean install site -Pcheckstyle,coverage,pmd,dist` worked fully for me

2024-12-19 18:45 UTC, sambish5 approved these changes
works for me!

2024-12-19 20:26 UTC, merged