Adding support to link a tld to a child IBDO for inheriting parameters
NationalSecurityAgency/emissary pull request #1016
Opened 2024-11-25 16:21 UTC by rpg36

2024-11-26 12:05 UTC, fbruton commented
Recommend to close this PR, open https://github.com/NationalSecurityAgency/emissary/pull/919, rename this branch the referenced by 919 and force push this branch.

2024-11-26 12:07 UTC, fbruton requested changes
Include changes in PR https://github.com/NationalSecurityAgency/emissary/pull/919

2024-12-26 13:47 UTC, fbruton approved these changes

2025-01-07 15:22 UTC, fbruton submitted a review, later dismissed
Will reapprove with unit-tests

2025-01-07 18:01 UTC, drivenflywheel requested changes
Minor cleanup requested, new code needs some test coverage

2025-01-07 22:15 UTC, drivenflywheel approved these changes
Thanks for the test coverage!

2025-01-08 03:23 UTC, jpdahlke approved these changes

2025-01-08 03:23 UTC, merged