Deprecate IBaseDataObjectHelper.clone() that allows partial clones.
NationalSecurityAgency/emissary pull request #1018
Opened 2024-12-02 19:41 UTC by jdcove2

This PR deprecates the IBaseDataObjectHelper.clone() method that allows for partial clones. Partial clones were implemented to allow cloning that matched the now deprecated BaseDataObject.clone() method. A search of the code bases did not show any instance where IBaseDataObjectHelper.clone() was called for a partial clone except for in the IBaseDataObjectHelperTest class. Therefore, only full clones seem to be needed and partial clones should be removed.

2024-12-03 18:28 UTC, sambish5 submitted a review, later dismissed

2024-12-03 21:26 UTC, drivenflywheel requested changes

2024-12-03 21:26 UTC, drivenflywheel commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +        return clone(iBaseDataObject, true);
I'm not a fan having the new overload reference the very method we're deprecating.  Maybe we should refactor the existing one by extracting two supporting methods that both overloads can use.  Something like the following signatures:
```java
private static copyBasicFields(final IBaseDataObject src, final IBaseDataObject dest) {
    // body would be current lines 66-87 
}
private static copyNonBasicFields(final IBaseDataObject src, final IBaseDataObject dest) {
    // body would be current lines 90-106
}
```
With that change, this overload would strip down to the following:
```java
 public static IBaseDataObject clone(final IBaseDataObject src) {
    Validate.notNull(src, "Required: src not null");
    IBaseDataObject dst = new InternalIdBaseDataObject(src.getInternalId());
    copyBasicFields(src, dst);
    copyNonBasicFields(src, dst);
    retrun dst;
}
```
The original now-deprecated overload would become this:
```java
 public static IBaseDataObject clone(final IBaseDataObject src, final boolean fullClone) {
    Validate.notNull(src, "Required: src not null");
    IBaseDataObject dst = fullClone ? new InternalIdBaseDataObject(src.getInternalId()) : DataObjectFactory.getInstance();
    copyBasicFields(src, dst);
    if (fullClone) {
        copyNonBasicFields(src, dst);
    }
    retrun dst;
}
```

After the deprecated overload is removed, we can collapse those private methods into the remaining `clone` method

2024-12-03 21:26 UTC, drivenflywheel commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +     * @deprecated
```suggestion
     * @deprecated prefer {@link #clone(IBaseDataObject)}
```

2024-12-03 21:26 UTC, drivenflywheel commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +    @Deprecated
```suggestion
    @Deprecated(forRemoval = true)
```

2024-12-05 15:30 UTC, drivenflywheel submitted a review, later dismissed

2024-12-05 15:55 UTC, jpdahlke approved these changes

2024-12-05 16:04 UTC, jpdahlke requested changes

2024-12-05 16:04 UTC, jpdahlke commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +    @Deprecated(forRemoval = true)
```suggestion
    @Deprecated
```
This makes it so the build doesn't warn on itself for this change.

2024-12-05 17:19 UTC, drivenflywheel approved these changes

2024-12-05 17:30 UTC, sambish5 approved these changes

2024-12-05 17:35 UTC, jpdahlke approved these changes

2024-12-05 17:35 UTC, merged