update tests to use java nio
NationalSecurityAgency/emissary pull request #102
Opened 2021-01-17 12:20 UTC by dev-mlb

Breaking https://github.com/NationalSecurityAgency/emissary/pull/34 into smaller PRs

2021-02-20 23:16 UTC, jpdahlke requested changes

2021-02-21 11:59 UTC, dev-mlb commented on src/test/java/emissary/config/ServiceConfigGuideTest.java
> +            Executrix.writeDataToFile(new String("OUTDIRTEST = " + dir + "/copilot/../output/testing.out").getBytes(), priname);
removed

2021-02-21 12:01 UTC, dev-mlb commented on src/test/java/emissary/config/ServiceConfigGuideTest.java
> +            Executrix.writeDataToFile(new String("OUTDIRTEST = " + dir + "/copilot/../output/testing.out").getBytes(), priname);
removed

2021-02-21 14:00 UTC, dev-mlb commented on src/test/java/emissary/config/FTestServiceConfigGuide.java
> +    public static Collection<Path> walk(Path dir, String ext) throws IOException {
moved

2021-02-21 17:06 UTC, fbruton approved these changes

2021-02-21 17:30 UTC, jpdahlke approved these changes

2021-02-21 17:33 UTC, merged