initialize static instance of EmissaryServer
NationalSecurityAgency/emissary pull request #1024
Opened 2024-12-16 21:00 UTC by jpdahlke

- removes the need for node.mode system property (get from command or default value)
- no longer need to check namespace binding to determine state
- deprecate stop/status methods for future cleanup

Pulled out of https://github.com/NationalSecurityAgency/emissary/pull/900 but stops short of changing mode to enum and changing command validator.

2024-12-17 13:53 UTC, dev-mlb requested changes
nits, but otherwise looks good

2024-12-17 13:53 UTC, dev-mlb commented on src/main/java/emissary/server/EmissaryServer.java
> +    private static EmissaryServer emissaryServer;
@SuppressWarnings("NonFinalStaticField")

2024-12-17 13:53 UTC, dev-mlb commented on src/main/java/emissary/pickup/WorkSpace.java
>                  } catch (Exception ex) {
Catch Runtime or add @SuppressWarnings("CatchingUnchecked")

2024-12-26 18:09 UTC, dev-mlb approved these changes

2025-01-07 17:04 UTC, fbruton requested changes
Recommend suggesting alternative methods in the Javadoc for deprecated methods where applicable.

2025-01-07 17:30 UTC, jpdahlke commented
> Recommend suggesting alternative methods in the Javadoc for deprecated methods where applicable.

Some of these have no other option and will be removed as part of future updates. I marked them as Deprecated vs removing them to reduce the overall scope of changes. I would be happy to address this in the next round of changes.

2025-01-07 17:36 UTC, fbruton approved these changes

2025-01-07 17:41 UTC, merged