Docker cleanup
NationalSecurityAgency/emissary pull request #130
Opened 2021-03-30 16:13 UTC by LightSeekerSC

Moving docker-related files to contrib and out of the base directory

2021-04-02 13:11 UTC, dev-mlb requested changes

2021-04-02 13:11 UTC, dev-mlb commented on pom.xml
> +              <buildArgs>
You can remove the buildArgs, b/c they are not used in the Dockerfile anymore.

2021-04-02 17:32 UTC, dev-mlb approved these changes

2021-04-05 12:59 UTC, jdcove2 approved these changes

2021-04-05 17:46 UTC, merged