Update to commons-pool2
NationalSecurityAgency/emissary pull request #142
Opened 2021-04-26 15:53 UTC by jpdahlke

2021-04-26 16:33 UTC, FineAndDandy approved these changes

2021-04-27 18:36 UTC, fbruton requested changes

2021-04-27 18:36 UTC, fbruton commented on src/main/java/emissary/pool/MobileAgentFactory.java
> +        if (!o.getObject().isInUse()) {
simplify with ```return !o.getObject().isInUse()```

2021-04-27 19:00 UTC, jpdahlke commented on src/main/java/emissary/core/MobileAgent.java
>      static final long serialVersionUID = 2656898442450171891L;
The IMobileAgent interface itself is serializable and runnable. I had removed these this due to redundancy.

2021-04-27 19:34 UTC, fbruton approved these changes

2021-04-27 19:43 UTC, merged