Add max of 50 to computed agents.
NationalSecurityAgency/emissary pull request #157
Opened 2021-06-14 17:10 UTC by cfkoehler

The configurable property can override this.

2021-06-14 20:56 UTC, jpdahlke requested changes
Please add a unit test. Recommend possibly creating a getMaxMemory() method to leverage/override in test to provide maxMem value rather than messing with the Runtime.

2021-07-23 13:59 UTC, cfkoehler commented
Added a test class and test's for the computePoolSize. Change it to take in a parameter of max memory.

2021-07-23 19:42 UTC, jdcove2 approved these changes

2021-09-29 15:31 UTC, jpdahlke commented on src/main/java/emissary/pool/AgentPool.java
> +    protected static int computePoolSize(final long maxMemoryInBytes, final Integer propertyOverride) {
Does poolSizeOverride make more sense?

2021-09-29 15:53 UTC, jpdahlke commented on src/test/java/emissary/pool/AgentPoolTest.java
> +        assertEquals(expectedPoolSize, AgentPool.computePoolSize(maxMemoryInBytes, propertyOverride), "Pool Size Calculation is not as");
This looks like:
`
Pool Size Calculation is not as ==> expected: <expected val> but was: <actual val>
`
Is this what was desired? "Pool Size Calculation Error"?
`
Pool Size Calculation Error ==> expected: <expected val> but was: <actual val>
`

2021-09-29 17:00 UTC, jpdahlke approved these changes

2021-09-29 17:01 UTC, merged