Allow service providers to initialize Emissary Server
NationalSecurityAgency/emissary pull request #215
Opened 2022-04-05 01:00 UTC by fbruton

2022-04-05 15:45 UTC, drivenflywheel requested changes
I like this approach - it's very clean.  The only changes I'd suggest are some Javadoc comments, particularly on the `InitializationProvider` interface, clarifying what this construct provides (e.g., why this helps).  In that comment it might be useful to restate that implementing classes should be registered in the _src/main/resources/META-INF/services/emissary.spi.InitializationProvider_ file as a reminder for future implementations.

2022-04-05 16:31 UTC, fbruton commented
> Reminder: this will conflict with #178, although it should be easy to resolve the conflict

I agree, but I think #178 should be declined.

2022-04-07 18:43 UTC, drivenflywheel approved these changes

2022-04-08 14:44 UTC, fbruton commented on src/main/java/emissary/spi/JavaCharSetInitializationProvider.java
> +        logger.debug("Initialized charset mapping subsystem...");
Added a log info statement to the for loop to ensure that all invoked service providers get logged.

2022-04-08 17:38 UTC, jpdahlke approved these changes

2022-04-08 17:40 UTC, merged