JUnit 5 :: utils package
NationalSecurityAgency/emissary pull request #230
Opened 2022-04-25 21:17 UTC by dev-mlb

2022-04-26 21:23 UTC, ukengineer925 approved these changes

2022-05-10 20:37 UTC, drivenflywheel requested changes
Minor cleanup suggested.  Overall looks good

2022-05-10 20:37 UTC, drivenflywheel commented on src/test/java/emissary/util/shell/ExecutrixTest.java
>          File f = new File(TMPDIR + "/foo.dat");
(Outside the PR scope, but these cleanup statements should be in a `finally` block because they won't be executed if an earlier assertion fails.)

2022-05-12 18:03 UTC, andrewbp commented on src/test/java/emissary/util/LineTokenizerTest.java
> +        assertNull(lt.nextToken(), "No remaining tokens");
I know it's not yours, but this messages seems to indicate a success rather than a failure.

2022-05-12 18:52 UTC, andrewbp approved these changes

2022-05-26 13:44 UTC, drivenflywheel approved these changes

2022-05-26 13:56 UTC, merged