JUnit5 :: place & roll packages
NationalSecurityAgency/emissary pull request #232
Opened 2022-04-25 21:24 UTC by dev-mlb

2022-04-26 21:34 UTC, ukengineer925 approved these changes

2022-05-12 19:12 UTC, andrewbp commented on src/test/java/emissary/place/MultiFileUnixCommandPlaceTest.java
> +        // empty catch block
Relevant catch block was removed.

2022-05-12 20:34 UTC, andrewbp approved these changes

2022-05-13 16:04 UTC, smcgrattan requested changes

2022-05-13 16:04 UTC, smcgrattan commented on src/test/java/emissary/place/ServiceProviderPlaceTest.java
> +            assertTrue(proxies.contains("TPROXY"), "Proxies contains original in set");
failure message should be does not contain (next 3 as well)

2022-05-17 16:00 UTC, smcgrattan approved these changes

2022-05-18 20:24 UTC, merged