JUnit5 :: core package
NationalSecurityAgency/emissary pull request #237
Opened 2022-05-02 19:19 UTC by dev-mlb

2022-05-20 15:22 UTC, jdcove2 approved these changes

2022-05-26 16:10 UTC, arp-0984 requested changes

2022-05-26 16:53 UTC, dev-mlb commented on src/test/java/emissary/core/FTestMovingAgent.java
> +        assertTrue((ws.getStatus() == HttpStatus.SC_OK), "welcome.jsp must return good status");
fixed

2022-05-26 16:53 UTC, arp-0984 approved these changes

2022-05-26 17:37 UTC, merged