Cleaned up content/unnecessary logging - Emissary Logs
NationalSecurityAgency/emissary pull request #249
Opened 2022-05-24 13:26 UTC by sambish5

Cleaned up content/unnecessary logging found throughout the entirety of the Emissary program. Any classes that were altered, I went through and parameterized all logs in that given class.

_*Any files with open content logging PRs not included*_

2022-05-26 16:22 UTC, jpdahlke requested changes
I'd make another pass over these files as I think we are being to aggressive in the removals. I added some comments to that effect.

Does anyone else care to weigh in on their expectations to help guide this effort?

2022-05-26 16:22 UTC, jpdahlke commented on src/main/java/emissary/kff/KffChainLoader.java
> -            logger.debug("KFF Chain loaded with " + theInstance.size() + " filter using algorithms " + theInstance.getAlgorithms());
This one seems ok to me just parameterize?

2022-05-26 16:22 UTC, jpdahlke commented on src/main/java/emissary/kff/KffChainLoader.java
> -                    logger.error("Unknown kff type " + kffType);
This one also seems ok, just needs an update.

2022-05-26 16:22 UTC, jpdahlke commented on src/main/java/emissary/output/filter/AbstractFilter.java
> -    protected static Logger slogger = LoggerFactory.getLogger(AbstractFilter.class);
These don't seem to have content, just types, etc. I might have to revisit what we say is content, but I'm not sure this class counts.

2022-05-26 16:22 UTC, jpdahlke commented on src/main/java/emissary/parser/FillingNIOParser.java
> -            logger.debug("Compacted buffer: sessionStart/chunkStart/writeOffset = {}/{}/{}", sessionStart, chunkStart, writeOffset);
Aren't these positional only?

2022-06-29 10:17 UTC, dev-mlb submitted a review, later dismissed

2022-06-29 10:17 UTC, dev-mlb commented on src/main/java/emissary/command/validator/ServerModeValidator.java
> +                // LOG.error("Unknown mode: {}", value);
you can remove this and the logger declaration on line 10

2022-08-11 02:23 UTC, jpdahlke commented
Circling back to this PR, I think I'm good with everything except:

- revert ServerModeValidator.java back to original form (this message is helpful)
- ServiceConfigGuide should only be printing key/value information provided in the config files themselves so I think it's safe to leave the log contents alone
- In HDMobileAgent, the `logger.isDebugEnabled()` blocks can be restored. They are helpful for routing and should only contain proxy information, not content.
- TikaFilePlace/UnixFilePlace, restore the commented out lines and their content. Identification information like this should be ok.
- Restore removed statements in AbstractFilter
- Restore the large `logger.isDebugEnabled()` block in ConstructorLookupCache for types/params
- Restore the removed statements from the TypeEngine class. These are helpful when wiring engines up.

For anything you restore from the above list, the reformatting/parameterization changes of the statements are fine.

2022-08-13 03:35 UTC, jpdahlke commented on src/main/java/emissary/config/ServiceConfigGuide.java
> +            logger.debug("ServiceConfigGuide::handleNewEntry -- FileFlavorList = _+{}", fileFlavorList);
This looks like a typo?

2022-08-16 14:15 UTC, drivenflywheel approved these changes
Looks good (aside from the one remaining typo that Jason noted)

2022-08-18 22:01 UTC, jpdahlke approved these changes

2022-08-18 22:02 UTC, merged