remove windows support
NationalSecurityAgency/emissary pull request #255
Opened 2022-06-03 18:57 UTC by dev-mlb

2022-06-13 13:37 UTC, cfkoehler approved these changes
Looks good to me. I searched through and could not find any other references to Windows

2022-06-13 22:18 UTC, drivenflywheel requested changes
Overall looks good, just some straggler pieces to clean up.  Will be nice to have this gone.

2022-06-13 22:18 UTC, drivenflywheel commented on src/main/java/emissary/util/shell/Executrix.java
> -                                tmpNames[DIR].substring(0, colPos + 1) + " && cd " + tmpNames[DIR] + " && " + CYGHOME + "/bin/bash -c '" + c + "'"};
Line 60 which populates `CYGHOME` can also go:
```
public static final String CYGHOME = System.getProperty("CYGHOME", "c:/cygwin").replaceAll("\\Q\\\\E", "/");
```

2022-06-14 13:47 UTC, dev-mlb commented on src/main/java/emissary/util/shell/Executrix.java
> -                                tmpNames[DIR].substring(0, colPos + 1) + " && cd " + tmpNames[DIR] + " && " + CYGHOME + "/bin/bash -c '" + c + "'"};
done

2022-06-14 13:48 UTC, dev-mlb commented on src/main/java/emissary/pickup/file/FilePickUpClient.java
> +    // place on unix like systems where the path need
done

2022-06-15 19:10 UTC, ukengineer925 submitted a review, later dismissed

2022-10-04 15:44 UTC, drivenflywheel submitted a review, later dismissed
LGTM - Adios, Windows!

2023-08-11 16:31 UTC, drivenflywheel approved these changes

2023-08-17 09:56 UTC, cfkoehler approved these changes

2023-08-18 17:35 UTC, merged