updated json output filter
NationalSecurityAgency/emissary pull request #265
Opened 2022-06-26 11:57 UTC by dev-mlb

2022-07-01 21:33 UTC, andrewbp requested changes

2022-07-01 21:33 UTC, andrewbp commented on src/main/java/emissary/output/filter/JsonOutputFilter.java
>              // check the white/black list first
This line seems to have (understandably) escaped the search/replace.

2022-07-14 17:12 UTC, andrewbp submitted a review, later dismissed

2022-10-04 15:48 UTC, drivenflywheel submitted a review, later dismissed

2023-09-24 15:12 UTC, jpdahlke commented on src/main/java/emissary/output/filter/JsonOutputFilter.java
>          private static final long serialVersionUID = 1L;
Should we make this inner class static while we are in here?

2023-12-12 13:31 UTC, jpdahlke approved these changes

2023-12-12 13:34 UTC, merged