sonarlint :: fix issues for jdomutil
NationalSecurityAgency/emissary pull request #289
Opened 2022-07-28 12:10 UTC by dev-mlb

2022-08-09 16:46 UTC, arp-0984 approved these changes

2022-08-11 22:09 UTC, jpdahlke requested changes
Kind of a nit, but is there a chance we can re-order/sort the methods in the extending util classes so that it's easier to find the method signatures we want? It was troublesome to diff the two side by side.

2022-08-11 22:09 UTC, jpdahlke commented on src/main/java/emissary/util/xml/AbstractJDOMUtil.java
> +     * Create a JDOM element, protectign the data with encoding if needed
```suggestion
     * Create a JDOM element, protecting the data with encoding if needed
```

2022-08-26 16:25 UTC, jpdahlke approved these changes

2022-08-26 16:26 UTC, merged