Created GitRepositoryState struct for storing git properties and log Git version during server startup
NationalSecurityAgency/emissary pull request #310
Opened 2022-09-07 23:16 UTC by cfkoehler

Knowing what version of emissary was actually deployed and running would have been helpful in troubleshooting an issue today.
The goal of this PR was to use the git.properties file that is created by the git-commit-id plugin and store the values in a way that is accessible by the running application. 

I did not create tests yet for GitRepositoryState() If that is something that is deemed necessary then I will do that.

2022-09-07 23:18 UTC, cfkoehler commented on src/main/java/emissary/util/GitRepositoryState.java
> +public class GitRepositoryState {
TODO: Add a javadoc description

2022-09-10 11:17 UTC, dev-mlb requested changes

2022-09-10 11:17 UTC, dev-mlb commented on src/main/java/emissary/util/GitRepositoryState.java
> +    public static GitRepositoryState getRepositoryState() {
Maybe allow the properties file to be passed in.
```suggestion
    public static GitRepositoryState getRepositoryState(String gitProperties) {
```

2022-09-11 10:32 UTC, dev-mlb commented on src/main/java/emissary/command/ServerCommand.java
> +            LOG.info("Starting Emissary Server - version: {} - built on {} - git hash: {}", GitRepositoryState.getRepositoryState().getBuildVersion(),
One last thought - I'm thinking we should move this to a location that is easier to override/update. For instance, we could add a method like dumpVersionInfo and add it after dumpBanner in Emissary.java to get:
```
|  ___|  \/  |_   _/  ___/  ___|/ _ \ | ___ \ \ / /
| |__ | .  . | | | \ `--.\ `--./ /_\ \| |_/ /\ V / 
|  __|| |\/| | | |  `--. \`--. \  _  ||    /  \ /  
| |___| |  | |_| |_/\__/ /\__/ / | | || |\ \  | |  
\____/\_|  |_/\___/\____/\____/\_| |_/\_| \_| \_/  

Emissary version: 7.9.0-SNAPSHOT built on 2022-09-10T10:39:15+0000 git hash: edaa856
```
This way we could output the version info for an implementation pretty easy - something like:
```
\___ /_,___/__,_/_/ /_/ /_/_/____/ ___/

Emissary version: 7.9.0-SNAPSHOT built on 2022-09-10T10:39:15+0000 git hash: edaa856
Implementation version: 0.0.1-SNAPSHOT built on 2022-09-10T11:12:34+0000 git hash: 1234567
``` 
Thoughts?

2022-09-11 20:24 UTC, dev-mlb commented on src/main/java/emissary/Emissary.java
> +            LOG.info(GitRepositoryState.dumpVersionInfo(GitRepositoryState.getRepositoryState()));
Make this line a method, and I think we're good to go. That way in an implementation we can call:
```
@Override
protected void dumpVersionInfo() {
    super.dumpVersionInfo();
    LOG.info(
       GitRepositoryState.dumpVersionInfo(
           GitRepositoryState.getRepositoryState("<implementation>.git.properties")
        )
    );
}
```

2022-09-13 10:19 UTC, dev-mlb approved these changes

2022-09-14 15:35 UTC, fbruton approved these changes

2022-09-16 17:13 UTC, jpdahlke commented
I will say, it's a bit jarring to see my user name come up in the logs. We might want to see how a release goes or maybe remove that bit.

2022-09-16 17:15 UTC, merged

2022-09-16 17:34 UTC, cfkoehler commented
> I will say, it's a bit jarring to see my user name come up in the logs. We might want to see how a release goes or maybe remove that bit.

We can over ride the output in different emissary implementations thanks to @dev-mlb feedback.
Though it is handy when deploying a custom build to validate the version running is what is expected as compared to another SNAPSHOT build with the same version number.