updates based on sonarlint warnings
NationalSecurityAgency/emissary pull request #339
Opened 2022-10-28 19:40 UTC by dev-mlb

2022-11-15 12:06 UTC, fbruton approved these changes

2022-11-16 21:41 UTC, andrewbp requested changes
![image](https://user-images.githubusercontent.com/88818760/202300414-81fb2e01-6128-451e-82c5-cfc1c7746a60.png)

Unsure about the ramifications of the second one, but I added the remove() call at the end of the respective method and did not see an issue.

2022-12-17 00:36 UTC, fbruton approved these changes
Looks good. Will need to resolve merge conflicts.

2022-12-21 10:49 UTC, cfkoehler approved these changes

2022-12-29 14:08 UTC, fbruton approved these changes

2022-12-29 14:13 UTC, jpdahlke approved these changes

2022-12-29 14:14 UTC, merged