Refactor Stage to be an enum (Closes #1877)
NationalSecurityAgency/emissary pull request #369
Opened 2022-12-12 20:58 UTC by drivenflywheel

Replaces #338

2022-12-12 22:34 UTC, andrewbp submitted a review, later dismissed

2022-12-16 20:22 UTC, drivenflywheel commented on src/main/java/emissary/core/MobileAgent.java
> -    public static final String AGENT_THREAD = "MobileAgent-".intern();
String literals are always interned, so these are redundant calls.  (Not technically within the scope of the original request, but these aren't numerous).

2023-01-20 13:10 UTC, fbruton submitted a review, later dismissed

2023-03-28 13:22 UTC, ldhardy requested changes
rebase please

2023-03-28 13:39 UTC, ldhardy commented
> > rebase please
> 
> FYI I think any member of the repo can click the rebase button. Click the dropdown next to 'Update Branch' and 'Update with Rebase'

I wasn't sure if that was a passive aggressive move or not.  Culturally.  I'm willing to try it so I can give feedback as long as it's not perceived as guache.

2023-03-28 13:52 UTC, drivenflywheel commented
> I wasn't sure if that was a passive aggressive move or not. Culturally. I'm willing to try it so I can give feedback as long as it's not perceived as gauche.

You assume we know what "gauche" means. 😄

2023-03-28 13:56 UTC, ldhardy approved these changes
👍🏽

2023-03-28 15:50 UTC, andrewbp approved these changes

2023-04-27 22:42 UTC, jpdahlke commented
This should integrate with no changes downstream.

2023-04-27 22:44 UTC, merged