sonarlint :: jni package
NationalSecurityAgency/emissary pull request #409
Opened 2023-02-01 21:03 UTC by dev-mlb

2023-02-02 13:20 UTC, fbruton approved these changes

2023-02-10 16:10 UTC, jdcove2 approved these changes

2023-02-12 18:22 UTC, jpdahlke commented on src/main/java/emissary/jni/JNI.java
> +            throw (new UnsatisfiedLinkError("Unable to retrieve dependencies for {}" + filename + " : {}" + errorMsg[0]));
Yes, I think this should be addressed.

2023-02-12 18:23 UTC, jpdahlke commented on src/main/java/emissary/jni/JNI.java
> +            logger.debug("Unable to link retrieved {}", fullPathName, e);
It's probably not a big deal, but this does appear to drop the `:`

2023-02-12 20:03 UTC, jpdahlke requested changes
Minor cleanup

2023-02-18 23:40 UTC, jpdahlke approved these changes

2023-02-21 13:25 UTC, jdcove2 approved these changes

2023-02-22 02:27 UTC, merged