update tika version to 2.x
NationalSecurityAgency/emissary pull request #425
Opened 2023-03-02 02:47 UTC by smcgrattan

2023-03-03 17:05 UTC, andrewbp approved these changes

2023-03-04 13:37 UTC, fbruton requested changes

2023-03-04 13:37 UTC, fbruton commented on pom.xml
> +        <exclusions>
Suggest removing exclusion in favor of the following :

```
<dep.jakarta.activation.version>1.2.2</dep.jakarta.activation.version>
```
```
      <dependency>
        <groupId>jakarta.activation</groupId>
        <artifactId>jakarta.activation-api</artifactId>
        <version>${dep.jakarta.activation.version}</version>
      </dependency>
```

2023-03-04 13:37 UTC, fbruton commented on pom.xml
> +    <dep.guava.version>30.1.1-jre</dep.guava.version>
```suggestion
```

2023-03-08 14:26 UTC, fbruton submitted a review, later dismissed

2023-03-29 12:32 UTC, fbruton requested changes

2023-03-29 12:32 UTC, fbruton commented on pom.xml
> +    <dep.tika.version>2.3.0</dep.tika.version>
```suggestion
    <dep.tika.version>2.3.0</dep.tika.version>
    <dep.versions.maven.plugin.version>2.14.2</dep.versions.maven.plugin.version>
```

2023-04-04 15:21 UTC, jpdahlke commented
https://github.com/NationalSecurityAgency/emissary/pull/447

2023-04-04 15:21 UTC, closed without merging