#1757 - Allow '+' in IBDO Form name
NationalSecurityAgency/emissary pull request #502
Opened 2023-06-20 15:04 UTC by aL118

Added + to the regex that checks if valid form name and updated unit test. Also updated some comments.

2023-06-20 18:32 UTC, drivenflywheel requested changes
Looks good overall.  Would like to make some assertion messages less ambiguous.

2023-06-20 18:32 UTC, drivenflywheel commented on src/test/java/emissary/util/PayloadUtilTest.java
> +        assertTrue(PayloadUtil.isValidForm(alphaLow), "Lower case alpha characters are valid");
I think we should alter each messages in this test to more clearly indicate what the expected result is. The original and proposed messages are ambiguous regarding whether they're stating desired vs observed behavior, but we can take away the ambiguity:
```suggestion
        assertTrue(PayloadUtil.isValidForm(alphaLow), "Lower case alpha characters are expected to be valid");
```
or 
```suggestion
        assertTrue(PayloadUtil.isValidForm(alphaLow), "Expected lower case alpha characters to be valid");
```

2023-06-20 18:32 UTC, drivenflywheel commented on src/test/java/emissary/util/PayloadUtilTest.java
> +        assertTrue(PayloadUtil.isValidForm("+"), "Plus are valid");
```suggestion
        assertTrue(PayloadUtil.isValidForm("+"), "'+' is expected to be a valid form character");
```

2023-06-20 20:51 UTC, aL118 commented
Forgot to add closes [#502](https://github.com/NationalSecurityAgency/burrito-grande/issues/1676)
Also just realized that title had the wrong issue number so it's been fixed.

2023-06-21 08:41 UTC, ldhardy approved these changes
Those previous test assertion messages were completely opposite of the expected behavior, huh?  That's confusing, glad it's fixed now.

2023-06-21 14:32 UTC, drivenflywheel approved these changes
Looks great.  Ready to ship. 🚀

2023-06-23 12:56 UTC, merged