Add font encoding verification to ExtractionTest
NationalSecurityAgency/emissary pull request #506
Opened 2023-06-24 01:24 UTC by fbruton

2023-06-26 19:11 UTC, jpdahlke requested changes

2023-06-26 19:11 UTC, jpdahlke commented on src/test/java/emissary/test/core/junit5/ExtractionTest.java
> +        if (fontEncoding != null && fontEncoding.length() > 0) {
```suggestion
        if (StringUtils.isNotBlank(fontEncoding)) {
```
Or did I miss something?

2023-06-26 19:21 UTC, drivenflywheel commented on src/test/java/emissary/test/core/junit5/ExtractionTest.java
> +        if (fontEncoding != null && fontEncoding.length() > 0) {
Everything else in this PR looks GTG

2023-06-26 19:39 UTC, drivenflywheel submitted a review, later dismissed

2023-06-27 16:09 UTC, drivenflywheel approved these changes

2023-06-27 17:44 UTC, merged