first commit
NationalSecurityAgency/emissary pull request #514
Opened 2023-07-07 13:57 UTC by aL118

Added necessary picocli annotations and mostly replaced jcommander in Emissary.java
Tracking issue: #513

2023-07-18 23:35 UTC, cfkoehler commented on pom.xml
I know this is still draft so please forgive me if I am providing feedback too early.

I believe Jcommander can be removed from the pom with all these changes.

2023-07-18 23:35 UTC, cfkoehler commented on src/main/java/emissary/Emissary.java
> +import emissary.command.*;
We prefer not to have star imports. Might need to adjust a setting in your IDE to avoid it auto converting to them

2023-07-19 13:45 UTC, aL118 commented on pom.xml
It's all good! Thanks for the early feedback on this massive ticket!

2023-08-03 22:24 UTC, drivenflywheel requested changes
This is excellent work. The only thing it doesn't seem to address 100% cleanly is the case for which someone specifies a command but not a required parameter - i.e.:
```bash
emissary (pr/514 $=)]$  ./emissary config
 ________  ________ _____ _____  ___  ________   __
|  ___|  \/  |_   _/  ___/  ___|/ _ \ | ___ \ \ / /
| |__ | .  . | | | \ `--.\ `--./ /_\ \| |_/ /\ V / 
|  __|| |\/| | | |  `--. \`--. \  _  ||    /  \ /  
| |___| |  | |_| |_/\__/ /\__/ / | | || |\ \  | |  
\____/\_|  |_/\___/\____/\____/\_| |_/\_| \_| \_/  

Command threw an exception: [config]
picocli.CommandLine$MissingParameterException: Missing required option: '--place=<place>'
	at picocli.CommandLine$MissingParameterException.create(CommandLine.java:18621)
	at picocli.CommandLine$MissingParameterException.access$21200(CommandLine.java:18609)
	at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13624)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13587)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13873)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13769)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13564)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13532)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13427)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at emissary.Emissary.execute(Emissary.java:101)
	at emissary.Emissary.main(Emissary.java:161)
```

Ideally, that would instead render the usage for that command:
```bash
emissary (pr/514 *$=)]$  ./emissary config
 ________  ________ _____ _____  ___  ________   __
|  ___|  \/  |_   _/  ___/  ___|/ _ \ | ___ \ \ / /
| |__ | .  . | | | \ `--.\ `--./ /_\ \| |_/ /\ V / 
|  __|| |\/| | | |  `--. \`--. \  _  ||    /  \ /  
| |___| |  | |_| |_/\__/ /\__/ / | | || |\ \  | |  
\____/\_|  |_/\___/\____/\____/\_| |_/\_| \_| \_/  

Missing required option: '--place=<place>'
Detailed help for: config
Usage: <main class> config [-q] [--detailed] [--offline] [--ssl]
                           [-b=<projectBase>] [--binDir=<binDir>] [-c=<config>]
                           [--errorRoot=<errorDir>] [--flavor=<flavor>]
                           [-h=<host>] [-j=<jettyUserFile>]
                           [--logbackConfig=<logbackConfig>]
                           [--outputRoot=<outputDir>] [-p=<port>]
                           --place=<place> [-s=<scheme>] [COMMAND]
Test the configuration for a place
  -b, --projectBase=<projectBase>
                          defaults to PROJECT_BASE, errors if different
                          Default: /home/dakahle/git-repos/emissary/target
      --binDir=<binDir>   emissary bin dir, defaults to <projectBase>/bin
  -c, --config=<config>   config dir, comma separated if multiple, defaults to
                            <projectBase>/config
      --detailed          get verbose output when parsing the configs
                          Default: false
      --errorRoot=<errorDir>
                          root error directory, defaults to
                            <projectBase>/localerrors
      --flavor=<flavor>   emissary config flavor, comma separated for multiple
  -h, --host=<host>       http host
                          Default: localhost
  -j, --jettyuserfile=<jettyUserFile>
                          jetty-users file to load
      --logbackConfig=<logbackConfig>
                          logback configuration file, defaults to
                            <configDir>/logback.xml
      --offline           run the config command in offline mode (useful for
                            local testing)
                          Default: false
      --outputRoot=<outputDir>
                          root output directory, defaults to
                            <projectBase>/localoutput
  -p, --port=<port>       http port
                          Default: 8001
      --place=<place>     fully-qualified place
  -q, --quiet             hide banner and non essential messages
                          Default: false
  -s, --scheme=<scheme>   http scheme
                          Default: http
      --ssl               run node with SSL enabled, reads keystore and
                            keytstorepass from HTTPConnectionFactory.cfg
                          Default: false
Commands:
  help  Print commands or usage for subcommand
```

2023-08-08 08:59 UTC, ldhardy reviewed
There are changed included in this PR that don't seem related to the picocli effort.

2023-08-08 22:53 UTC, cfkoehler commented on src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
I think @ldhardy noticed this file changing.
Which are changes from this pr: https://github.com/NationalSecurityAgency/emissary/pull/523/files
So maybe a strange rebase is showing them in the diff here

2023-08-09 15:19 UTC, aL118 commented on src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
Yes, I did do a rebase when making the last change and a bunch of commits showed up (probably bc they were merged during the lifetime of this pr). Just did `git rebase master` and forced push my branch.

2023-08-11 09:14 UTC, cfkoehler approved these changes

2023-08-11 09:15 UTC, merged