add RELEASING.md document
NationalSecurityAgency/emissary pull request #526
Opened 2023-07-28 18:53 UTC by jpdahlke

2023-07-28 20:42 UTC, drivenflywheel requested changes
Minor suggestions.  They can be dismissed with little impact.

2023-07-28 20:42 UTC, drivenflywheel commented on RELEASING.md
> +  - Remove SNAPSHOT from the version and create scm tag
```suggestion
  - Remove the "-SNAPSHOT" suffix from the version and create scm tag
```

2023-07-28 20:42 UTC, drivenflywheel commented on RELEASING.md
> +Releases may have bugs or vulnerabilities with a high enough severity that requires a patch release to fix.
```suggestion
Releases may have bugs or vulnerabilities with a high enough severity that requires a patch release to fix. Patch releases can only be performed from a patch branch (described below).
```

2023-07-28 20:42 UTC, drivenflywheel commented on RELEASING.md
> +Iterative releases are not guaranteed to be stable, like snapshots, but allow for markers in the development stage and allow for testing and
Maybe?
```suggestion
Like snapshots, Iterative releases are not guaranteed to be stable, but allow for markers in the development stage and allow for testing and
```

2023-08-04 10:41 UTC, cfkoehler approved these changes

2023-08-08 22:46 UTC, merged

2023-08-09 08:43 UTC, ldhardy commented
I know this was already merged, but these instructions didn't include any details about the preferred way the patch makes it into the master branch.   Or was the idea that the change is made in master and then cherry picked into the patch branch?

2023-08-09 09:03 UTC, cfkoehler commented
> I know this was already merged, but these instructions didn't include any details about the preferred way the patch makes it into the master branch. Or was the idea that the change is made in master and then cherry picked into the patch branch?

That is the preferred way. But no reason we can’t be explicit about it in the doc. I can add a section describing that later today and put up a PR