Moving XMLCodec constants to their own classes
NationalSecurityAgency/emissary pull request #531
Opened 2023-08-04 14:27 UTC by sambish5

https://github.com/NationalSecurityAgency/emissary/pull/515#discussion_r1276517975
Done from this comment left on 515. Moved AnswerFile constants and method constants to separate classes.

2023-08-09 20:46 UTC, drivenflywheel commented
> Some suggestions...
> 
> * "AsnwerXMLFileElementNames" -> "IbdoXmlElementNames"
Disagree on this one.  IBDOs don't have element names, and these names are specific to our UnitTest/ExtractionTest/RegressionTest XML answer files.
> * "IBDOMethodNames" -> "IbdoMethodNames"
Meh, I find IBDOMethodNames to be more readable
> * Javadoc all of the constants in the above classes.
IMO, constants should only have Javadoc comments if those comments clarify usage or ambiguity.
> * Make the above two classes final.
> * Move ...ATTRIBUTE_NAME fields to IbdoXmlElementNames class.

2023-08-09 21:23 UTC, drivenflywheel requested changes
Good first pass, but I think we can further improve the readability with minimal effort.

2023-08-14 18:56 UTC, sambish5 commented on src/main/java/emissary/core/constants/AnswerXMLFileElementNames.java
> +    public static final String ANSWERS_ELEMENT_NAME = "answers";
Would you think it'd be smart to do this in IbdoMethodNames as well, to remove the `_METHOD_NAME` part? I think I'd keep the `SET` to keep it obvious they are setters

2023-08-14 21:10 UTC, drivenflywheel commented on src/main/java/emissary/core/constants/AnswerXMLFileElementNames.java
> +    public static final String ANSWERS_ELEMENT_NAME = "answers";
Yes, absolutely.  I thought my last review included a specific comment that we drop those suffixes and move `SET_` from the end to the front to mirror the actual method names. Only one referencing file to update. Good catch!

2023-08-18 17:28 UTC, merged