jetty 10
NationalSecurityAgency/emissary pull request #552
Opened 2023-09-01 20:32 UTC by dev-mlb

2023-09-08 14:58 UTC, fbruton requested changes
This transitive dependency is  a bit concerning. Does jersey need to be updated to 3.x?
```
[INFO] +- org.glassfish.jersey.containers:jersey-container-jetty-http:jar:2.40:compile
[INFO] |  +- org.glassfish.hk2.external:jakarta.inject:jar:2.6.1:compile
[INFO] |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.51.v20230217:compile
```

2023-09-08 14:58 UTC, fbruton commented on src/main/java/emissary/server/EmissaryServer.java
Remove throws `GeneralSecurityException` from  the `configureServer()` method.  Code was updated to catch and throw an `IOException`.

2023-09-09 11:32 UTC, dev-mlb commented on src/main/java/emissary/server/EmissaryServer.java
Done

2023-09-09 12:12 UTC, dev-mlb commented
> This transitive dependency is a bit concerning. Does jersey need to be updated to 3.x?
> 
> ```
> [INFO] +- org.glassfish.jersey.containers:jersey-container-jetty-http:jar:2.40:compile
> [INFO] |  +- org.glassfish.hk2.external:jakarta.inject:jar:2.6.1:compile
> [INFO] |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.51.v20230217:compile
> ```

Yeah, it's unfortunate but this code is deprecated and not in the next version of Jetty due to the new Async stuff. It is just this jar, which has only a few classes in it. If I upgrade to Jersey 3+, the Jakarta conversion starts which would probably be easier to take #550...

2023-09-14 19:33 UTC, jpdahlke commented
> > This transitive dependency is a bit concerning. Does jersey need to be updated to 3.x?
> > ```
> > [INFO] +- org.glassfish.jersey.containers:jersey-container-jetty-http:jar:2.40:compile
> > [INFO] |  +- org.glassfish.hk2.external:jakarta.inject:jar:2.6.1:compile
> > [INFO] |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.51.v20230217:compile
> > ```
> 
> Yeah, it's unfortunate but this code is deprecated and not in the next version of Jetty due to the new Async stuff. It is just this jar, which has only a few classes in it. If I upgrade to Jersey 3+, the Jakarta conversion starts which would probably be easier to take #550...

I think I would like to try going forward with Jetty 10 first even with this jar.

2023-09-14 23:36 UTC, cfkoehler approved these changes
I was not sure the best way to review this.
I started up a server with and without the new SniHost option and all seems to work as expected.

Also started up multiple emissary as a local cluster and that all seemed correct.

All the pom changes make sense when looking at the dependency tree.

2023-09-15 01:01 UTC, jpdahlke approved these changes
I integrated this downstream and don't see any immediate issues.

2023-09-15 01:02 UTC, merged