remove deprecated runcommand and main-runner
NationalSecurityAgency/emissary pull request #568
Opened 2023-09-09 14:56 UTC by dev-mlb

2023-09-12 14:12 UTC, drivenflywheel approved these changes

2023-09-24 14:52 UTC, jpdahlke requested changes
The commons-cli dependency can get removed with this as well it seems

2023-12-12 14:44 UTC, jpdahlke commented on src/main/java/emissary/Emissary.java
> +                        AgentsCommand.class, PoolCommand.class, VersionCommand.class, EnvCommand.class,
```suggestion
                        AgentsCommand.class, PoolCommand.class, VersionCommand.class, EnvCommand.class,
```

2023-12-12 14:53 UTC, jpdahlke approved these changes

2023-12-12 15:00 UTC, drivenflywheel approved these changes

2023-12-12 16:10 UTC, merged