remove what command
NationalSecurityAgency/emissary pull request #576
Opened 2023-09-10 12:40 UTC by dev-mlb

2023-09-22 09:32 UTC, cfkoehler submitted a review, later dismissed

2023-10-14 18:48 UTC, fbruton requested changes
Remove references to the `What` command from the`README`.

2023-12-12 00:30 UTC, cfkoehler approved these changes

2023-12-12 13:27 UTC, jpdahlke approved these changes

2023-12-12 13:27 UTC, merged