Add meaglint instructions to DEVELOPING.md and move settings to separate file
NationalSecurityAgency/emissary pull request #607
Opened 2023-10-05 11:29 UTC by cfkoehler

2023-10-05 11:30 UTC, cfkoehler commented on .mega-linter.yml
- [ ] Still working to see if I can move this to the linters directory. But not sure how to set the action to use it when moved away from repo root

2023-10-14 11:19 UTC, cfkoehler commented on DEVELOPING.md
> +3) Run MegaLinter from project root using project configuration `mega-linter-runner  -e 'LINTER_RULES_PATH=.github/linters' .`
```suggestion
3) Run MegaLinter from project root using project configuration `mega-linter-runner  -e 'EXTENDS=.github/linters/.mega-linter.yml' -p .`
```

2023-10-14 11:19 UTC, cfkoehler commented on DEVELOPING.md
> +* To have MegaLinter attempt to fix errors add the `--fix` option to the command: `mega-linter-runner  -e 'LINTER_RULES_PATH=.github/linters' --fix . `
```suggestion
* To have MegaLinter attempt to fix errors add the `--fix` option to the command: `mega-linter-runner  -e 'EXTENDS=.github/linters/.mega-linter.yml' --fix -p .`
```

2023-12-15 17:28 UTC, jpdahlke submitted a review, later dismissed

2023-12-26 13:00 UTC, Kevinnnnnnnnnnnnnnnn requested changes
Other than some language I found confusing in DEVELOPING.md, everything looks good to me!

2023-12-27 11:56 UTC, cfkoehler commented on DEVELOPING.md
> +changed files in PR's and the entire codebase on merge. To run the same linting rule set local following the following steps.
```suggestion
changed files in PR's and the entire codebase on merge. To run the same linting rule set locally, follow the steps bellow:
```

2023-12-27 16:44 UTC, fbruton commented on DEVELOPING.md
> +changed files in PR's and the entire codebase on merge. To run the same linting rule set locally, follow the steps bellow:
```suggestion
changed files in PR's and the entire code-base on merge. To run the same linting rule set locally, follow the steps below:
```

2023-12-27 16:45 UTC, fbruton submitted a review, later dismissed
Fix minor typo

2023-12-27 22:04 UTC, jpdahlke approved these changes

2023-12-28 16:32 UTC, Kevinnnnnnnnnnnnnnnn approved these changes

2023-12-28 16:56 UTC, merged