Add additional IBDO parameter diff options.
NationalSecurityAgency/emissary pull request #609
Opened 2023-10-05 18:07 UTC by jdcove2

Currently, IBaseDataObjectDiffHelper returns all of the parameter keys and values for both IBDO's if there is any difference. This can make finding the actually differences difficult if there are a lot of parameters.

This PR does the following:
1. Add an option to display only the keys that differ for both IBDO's.
2. Add an option to display only the keys and values that differ for both IBDO's.
3. Make No. 1 the default behavior instead of the current behavior.

2023-10-10 16:34 UTC, drivenflywheel commented
> 3\. Make No. 1 the default behavior instead of the current behavior.

We're replacing the default behavior with a new behavior; is there a way to explicitly get the current behavior or is the current behavior being abandoned?

2023-10-10 18:54 UTC, drivenflywheel requested changes
Minor tweaks suggested

2023-10-11 14:45 UTC, drivenflywheel submitted a review, later dismissed

2023-10-11 16:58 UTC, arp-0984 reviewed
Only minor comments, overall looks good though.

2023-10-11 16:58 UTC, arp-0984 commented on src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
> +    public static void keyValueMapDiff(final Map<String, Collection<String>> parameter1, final Map<String, Collection<String>> parameter2,
Do you think it would be helpful to add javadoc comments for these two functions?

2023-10-11 16:58 UTC, arp-0984 commented on src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
> +            differences.add(String.format("%s%s: %s : %s", identifier, ARE_NOT_EQUAL + "-Differing Keys/Valus", p1, p2));
```suggestion
            differences.add(String.format("%s%s: %s : %s", identifier, ARE_NOT_EQUAL + "-Differing Keys/Values", p1, p2));
```

2023-10-11 20:41 UTC, drivenflywheel approved these changes

2023-10-11 20:44 UTC, arp-0984 approved these changes

2023-11-07 11:00 UTC, merged