add a watch thread to test for stuck places
NationalSecurityAgency/emissary pull request #624
Opened 2023-11-15 19:38 UTC by dev-mlb

2023-11-16 17:19 UTC, drivenflywheel requested changes
I like this framework.  Tested locally by enabling DelayPlace and configuring 2 rules (DEFAULT -> Notify) , (DelayPlace -> KILL) rules.  Verified that both NOTIFY and KILL currently work, although I haven't tested KILL with a scenario that doesn't support thread interruption.

2023-11-16 18:13 UTC, dev-mlb commented on src/main/resources/emissary/core/Sentinel.cfg
> +DEFAULT_TIME_LIMIT = "60"
👍

2023-11-16 18:13 UTC, dev-mlb commented on src/main/resources/emissary/core/Sentinel.cfg
> +POLLING_INTERVAL = 5
👍

2023-11-16 18:13 UTC, dev-mlb commented on src/main/java/emissary/core/Sentinel.java
> +            this.place = place;
👍

2023-11-16 19:01 UTC, drivenflywheel approved these changes
Excellent stuff. My only remaining suggestions are cosmetic and could be deferred / ignored, although it would be useful to have durations to the log messages.

2023-11-17 12:26 UTC, drivenflywheel submitted a review, later dismissed
🔥 🔥

2023-11-17 19:57 UTC, fbruton commented on src/main/java/emissary/core/sentinel/rules/Rule.java
> +        logger.trace("Loaded {}", this);
I think it would be useful to know which rules were loaded.
```suggestion
        logger.info("Loaded {}", this);
```

2023-11-20 16:07 UTC, jpdahlke requested changes
Ones thing I noticed is that Idle agents do not seem to come into play when performing the ratio calculation such that a situation where there are 2 agents and only one is "stuck" and the threshold is .5, Sentinel will execute it's rule. That seems like it could impact shutdown depending on how it is configured. I would assume idle/exited threads should be removed from the calculation such that the ratio calculation is only performed against inUse threads.

The other thing I noticed was that having one long time stuck agent that by itself would not execute the rule (2 agents and a threshold of .75), as soon as a new agent comes in and matches the place name (regardless of how stuck it is) the rule is executed. It seems like the threshold count should not stand on its own and needs to be combined with the `overTimeLimit` check for each agent. Another way to say this might be, the threshold should not trigger on threads just based on a rule/name match, but are also old themselves.

2023-11-20 16:15 UTC, jpdahlke commented on src/main/resources/emissary/core/sentinel/Sentinel.cfg
> +ENABLED = true
```suggestion
ENABLED = false
```

2023-12-01 00:49 UTC, jpdahlke commented
> One thing I noticed is that Idle agents do not seem to come into play when performing the ratio calculation such that a situation where there are 2 agents and only one is "stuck" and the threshold is .5, Sentinel will execute its rule. That seems like it could impact shutdown depending on how it is configured. I would assume idle/exited threads should be removed from the calculation such that the ratio calculation is only performed against inUse threads.

Talking through this, I think I was thinking of this backwards. As agents become idle that would inflate the ratio of stuck threads and initiate a shutdown even sooner than expected. Keeping the math pinned to the total agent count is probably more correct (and more importantly, predictable).

2023-12-01 03:12 UTC, jpdahlke requested changes
Mostly small comments after our discussion

2023-12-04 16:10 UTC, jpdahlke approved these changes
I'm good with this as-is, you can resolve my comments and update in a follow up.

One other things to note for the future, 
TIME_LIMIT_MINUTES and RULE has a default which is quietly applied.  PLACE_THRESHOLD throws an error and shuts down emissary when not specified. PLACE_MATCHER disables the protocol and moves on when not specified and misnaming the rule also just disables the protocol. I'm not sure if this behavior should be more consistently managed or not. It's obvious what is wrong in all cases.

I think there is an ask to create some class level documentation or something on how this works/behaves. I believe the sample is enough for now to get moving. I don't suggest holding this up for that.

2023-12-04 17:46 UTC, jpdahlke approved these changes

2023-12-04 19:06 UTC, merged