Modifying the ObjectTrace logger to output a single message for a bundle instead of a message for each session
NationalSecurityAgency/emissary pull request #627
Opened 2023-11-27 16:23 UTC by arp-0984

Overloading the emitLifecycleEvent method because we do not yet have a IBDO object where we need to emit this message and we do not need it to output the fields we need. The old emitLifecycleEvent can probably be removed once this is fully integrated.

2023-11-28 00:19 UTC, fbruton requested changes

2023-11-28 00:19 UTC, fbruton commented on src/main/java/emissary/util/ObjectTracing.java
>          objectTraceLogger.info(appendEntries(jsonMap), "");
Update implementation to call newly created method to reduce duplication:
```
    public void emitLifecycleEvent(IBaseDataObject d, ObjectTracing.Stage stage) {
        
        emitLifecycleEvent(d.getFilename(), stage);
    }
```

2023-12-06 00:31 UTC, cfkoehler approved these changes
I integrated this with the upstream project and got single output per file which is expected

2023-12-14 23:02 UTC, fbruton approved these changes

2023-12-15 16:32 UTC, merged