sentinel updates and add tests
NationalSecurityAgency/emissary pull request #631
Opened 2023-12-06 21:12 UTC by dev-mlb

2023-12-11 12:42 UTC, jpdahlke commented on src/main/java/emissary/core/sentinel/Sentinel.java
> +                    .add("\"timeInMinutes\":" + timer)
confirming you intend this to print like: `"timeInMinutes":2` and not `"timeInMinutes":"2"`

2023-12-11 12:55 UTC, jpdahlke requested changes
Change look good, just minor nits.

2023-12-11 12:55 UTC, jpdahlke commented on src/main/java/emissary/core/sentinel/protocols/Protocol.java
> +import static emissary.core.sentinel.Sentinel.Tracker.getPlaceName;
Not needed?

2023-12-11 14:06 UTC, dev-mlb commented on src/main/java/emissary/core/sentinel/protocols/Protocol.java
> +import static emissary.core.sentinel.Sentinel.Tracker.getPlaceName;
Nuked

2023-12-12 13:18 UTC, jpdahlke approved these changes

2023-12-12 14:06 UTC, cfkoehler approved these changes

2023-12-12 14:53 UTC, merged