Add optional log checking to RegressionTest.
NationalSecurityAgency/emissary pull request #634
Opened 2023-12-14 15:46 UTC by jdcove2

This PR adds optional log checking to RegressionTest. It is disabled by default and enabled by overriding getLogbackLoggerName() and returning the name of the logger to track.

2023-12-26 18:47 UTC, arp-0984 approved these changes
Looks reasonable to me

2024-01-04 21:41 UTC, fbruton requested changes
Recommend updating an existing regression test to exercise this new feature.

2024-01-05 17:29 UTC, sambish5 approved these changes

2024-01-11 15:58 UTC, fbruton approved these changes

2024-01-11 21:48 UTC, drivenflywheel commented on src/test/java/emissary/test/core/junit5/RegressionTest.java
> +    protected String getLogbackLoggerName() {
We don't _need_ to change this, but this is a clumsy design pattern.  Why override a method if the goal is just to set a String value?  RegressionTest should just read a config file entry and use it to assign a field value.  That pattern is deeply ingrained in the emissary code base. 
To be honest, we should be doing the same with respect to generating answer files.  Requiring a `generateAnswers()` override just to toggle a boolean value is poor design, and makes devs write throwaway code.

```ini
LOGGER_TO_CAPTURE = "name of logger"
GENERATE_ANSWER_FILES = "true"
```

2024-01-12 16:03 UTC, drivenflywheel commented on src/test/java/emissary/test/core/junit5/RegressionTest.java
> +    protected String getLogbackLoggerName() {
Fine, skip the config file, use protected fields in RegressionTest.  This is Object-Oriented Design, but awful encapsulation.

2024-01-16 14:50 UTC, merged