Added empty string check
NationalSecurityAgency/emissary pull request #635
Opened 2023-12-19 20:15 UTC by SemperFidelisTyrannosaurus

2023-12-20 21:39 UTC, drivenflywheel commented
Consider permanently adding a multi-step entry to the bottom of the `magic` file, along with a corresponding UNKNOWN@2.dat file in src/test/resources/emissary/id/UnixFilePlaceTest that triggers the partial match.  If you want to overachieve, add a unit test that leverages the `LogbackTester` class to demonstrate that the exception is no longer thrown/logged.

2024-01-02 16:34 UTC, SemperFidelisTyrannosaurus commented
Added additional unit test to make sure exception wasn't thrown.  Unfortunately it doesn't seem like there is a way to confirm that there are no exceptions with the undepricated method in LogbackTester.  That should be fixed but may be outside the scope of this ticket.

2024-01-02 18:23 UTC, drivenflywheel commented
> ... it doesn't seem like there is a way to confirm that there are no exceptions with the undepricated method in LogbackTester. 

`logbackTester.checkLogList(Collections.emptyList());` ?

2024-01-02 22:11 UTC, SemperFidelisTyrannosaurus commented
> > ... it doesn't seem like there is a way to confirm that there are no exceptions with the undepricated method in LogbackTester.
> 
> `logbackTester.checkLogList(Collections.emptyList());` ?

Doh, misread the Validation at the the beginning of the method and didn't think to test it for myself.  updated.

2024-01-03 16:51 UTC, drivenflywheel commented on src/test/java/emissary/id/UnixFilePlaceTest.java
> +                fail("Cannot run test " + resource, ex);
Why "Cannot run test"?  This code can only be reached by running the test

2024-01-03 17:15 UTC, drivenflywheel requested changes
Minor cleanup suggested

2024-01-03 17:15 UTC, drivenflywheel commented on src/test/java/emissary/id/UnixFilePlaceTest.java
> +    void testException() throws IOException {
```suggestion
    void testMultiStepRuleAtBottomOfMagicFile() throws IOException {
```

2024-01-03 17:15 UTC, drivenflywheel commented on src/test/java/emissary/id/UnixFilePlaceTest.java
> +                processPreHook(payload, resource);
Remove unnecessary call
```suggestion
```

2024-01-03 17:15 UTC, drivenflywheel commented on src/test/java/emissary/id/UnixFilePlaceTest.java
> +                processPostHook(payload, resource);
Remove unnecessary call
```suggestion
```

2024-01-03 17:15 UTC, drivenflywheel commented on src/test/java/emissary/id/UnixFilePlaceTest.java
> +                processPostHook(payload, resource);
```suggestion
                processPostHook(payload, resource);
                assertTrue(StringUtils.isBlank(payload.getProcessingError()), "Expected no processing error");
```

2024-01-04 16:12 UTC, drivenflywheel approved these changes
🚀

2024-01-12 19:48 UTC, jpdahlke approved these changes

2024-01-12 19:53 UTC, drivenflywheel approved these changes

2024-01-16 14:57 UTC, merged