fix sentinel bug when matching on place
NationalSecurityAgency/emissary pull request #636
Opened 2023-12-20 18:38 UTC by dev-mlb

2023-12-21 17:42 UTC, drivenflywheel requested changes
Excellent functionality.  Tests could use some minor non-functional cleanup to help with future maintainability.

2023-12-21 17:42 UTC, drivenflywheel commented on src/test/java/emissary/core/sentinel/protocols/rules/AllMaxTimeTest.java
> +    void condition() {
(nit) This method's got a lot of redundant code.  Can make it somewhat less dense with a couple minor changes:
- create a `stats` variable to reuse for all the condition checks
```
final List<PlaceAgentStats> stats = List.of(lowerStats, upperStats);
```
- eliminate consecutive `when(pool.getCurrentPoolSize()).thenReturn(value);` calls that don't change the existing pool size. The noise obscures the intent of the assertions.   Might also be clarifying to wrap those in a `setPoollSize(pool, newSize)` helper method.

2023-12-21 17:42 UTC, drivenflywheel commented on src/test/java/emissary/core/sentinel/protocols/rules/AllMaxTimeTest.java
> +        upperStats.update(7);
When reading the assertions, it's hard to track the correlation between these magic numbers and the values used in the rule constructors.  Might be easier to follow if we added named values and used those when resetting the pool size or instantiating rules. If I'm having a hard time following while this code is new, I can imagine it being much harder for a new dev to follow it in the future.
```suggestion
        final int DEFAULT_TIME_LIMIT = 5;
        Protocol.PlaceAgentStats lowerStats = new Protocol.PlaceAgentStats("ToLowerPlace");
        lowerStats.update(DEFAULT_TIME_LIMIT);       // agent A
        lowerStats.update(DEFAULT_TIME_LIMIT + 3);   // agent B
        lowerStats.update(DEFAULT_TIME_LIMIT + 1);   // agent C

        Protocol.PlaceAgentStats upperStats = new Protocol.PlaceAgentStats("ToUpperPlace");
        upperStats.update(DEFAULT_TIME_LIMIT);     // agent X
        upperStats.update(DEFAULT_TIME_LIMIT + 2);  // agent Y
        
        final int TOTAL_BUSY_AGENTS = lowerStats.getCount() + upperStats.getCount();
```
```java        
        ...
        setPoolSize(pool, TOTAL_BUSY_AGENTS + 1);
        Rule rule = new AllMaxTime("rule1", "To(?:Lower|Upper)Place", DEFAULT_TIME_LIMIT, 1.0);
```

2023-12-21 20:23 UTC, drivenflywheel submitted a review, later dismissed

2023-12-27 17:51 UTC, drivenflywheel approved these changes

2023-12-27 22:03 UTC, jpdahlke approved these changes

2023-12-27 22:03 UTC, merged