Add ComparisonPlace.
NationalSecurityAgency/emissary pull request #644
Opened 2024-01-10 20:43 UTC by jdcove2

This PR adds ComparisonPlace. ComparisonPlace runs the configured two places and gives them identical IBDO's. ComparisonPlace then compares the output of the two places and logs any differences.

2024-02-09 13:52 UTC, cfkoehler commented
@jdcove2 why is this label as 'test-only' when this is a new place and feature. 
I would have expected to see this labeled as 'feature'. Probably something that will never be run on a production system but still doing more then just creating/modifying java test code.

Happy to be proven wrong. I have not fully digested this PR yet.

2024-02-12 17:59 UTC, drivenflywheel requested changes
Minor changes requested

2024-02-12 17:59 UTC, drivenflywheel commented on src/main/java/emissary/place/ComparisonPlace.java
> +        Validate.notNull(loggingIdentifier, LOGGING_IDENTIFIER + NOT_NULL_STRING);
These validation messages don't really tell the dev how to fix the misconfiguration. "PLACE_A_CLASSNAME == null not allowed!"  is not as instructive as "No configuration entry found with key PLACE_A_CLASSNAME"

2024-02-12 17:59 UTC, drivenflywheel commented on src/main/java/emissary/place/ComparisonPlace.java
> +    public List<IBaseDataObject> processHeavyDuty(IBaseDataObject ibdoA) throws ResourceException {
We need a comment either here or within the class Javadoc comment clearly detailing the side effects of having this place configured. 
- How does this place impact the IBDO and any children? 
- How should this place be registered with the routing/directory framework? 
  - What about "PlaceA" and "PlaceB"? 
  - Do any service proxies need to be modified?

2024-02-12 20:22 UTC, drivenflywheel reviewed
Need to rebase.   Unit tests in this PR were broken by PR #664, and merging this PR in its current state will prevent master from building.

2024-02-13 15:15 UTC, drivenflywheel approved these changes

2024-04-01 13:31 UTC, rpg36 approved these changes
Approving, but bringing up the concern that this place will introduce invisible places. So it might conflict with the work that was done recently to address invisible places.

2024-04-05 20:05 UTC, merged