Improve IBaseDataObjectHelper testing.
NationalSecurityAgency/emissary pull request #657
Opened 2024-01-25 20:37 UTC by jdcove2

This PR improves the testing of findPreferredData(...) and findPreferredDataByRegex(...) methods.

2024-01-29 20:22 UTC, SemperFidelisTyrannosaurus submitted a review, later dismissed

2024-01-29 22:50 UTC, drivenflywheel requested changes

2024-01-29 22:50 UTC, drivenflywheel commented on src/test/java/emissary/core/IBaseDataObjectHelperTest.java
> +        assertThrows(IllegalArgumentException.class, () -> IBaseDataObjectHelper.findPreferredData(null, emptyPreferredViews));
Wrong method called (probably a copy/paste error)

```suggestion
        assertThrows(IllegalArgumentException.class, () -> IBaseDataObjectHelper.findPreferredData(null,  new ArrayList<>()));
```

2024-01-30 19:48 UTC, drivenflywheel approved these changes

2024-02-06 15:10 UTC, SemperFidelisTyrannosaurus approved these changes

2024-02-09 20:29 UTC, merged