Add IBDO method to ensure data is available.
NationalSecurityAgency/emissary pull request #718
Opened 2024-03-06 17:30 UTC by jdcove2

This PR adds a method to IBaseDataObject and BaseDataObject that checks whether there is valid data and that it is non-zero in length.

2024-03-07 17:01 UTC, fbruton submitted a review, later dismissed

2024-03-07 18:12 UTC, drivenflywheel requested changes

2024-03-07 18:12 UTC, drivenflywheel commented on src/main/java/emissary/core/BaseDataObject.java
> +    }
Could we invert this logic and change its name to `hasContent`?  That name seems more intuitive to me, and it keeps the internals internal. (`getChannelSize` already includes the `getDataState()` check, so its inclusion here would be redundant).
```suggestion
    public boolean hasContent() throws IOException {
        return getChannelSize() > 0;
    }
```

2024-03-10 00:43 UTC, fbruton approved these changes

2024-03-11 15:28 UTC, drivenflywheel approved these changes

2024-03-18 18:15 UTC, merged