move to use 'blank space'
NationalSecurityAgency/emissary pull request #733
Opened 2024-04-02 13:40 UTC by jpdahlke

2024-04-02 13:43 UTC, sambish5 approved these changes

2024-04-02 15:19 UTC, drivenflywheel commented on src/main/java/emissary/util/DataUtil.java
> +     * Return true if the data slot is empty or just blank space and/or control chars
This is _(and already was)_ a misleading description of the functionality.  The underlying code doesn't examine individual characters at all:
```
    public static boolean isEmpty(@Nullable final byte[] data) {
        return (data == null) || (data.length == 0);
    }
```

2024-04-02 15:21 UTC, drivenflywheel requested changes

2024-04-02 15:21 UTC, drivenflywheel commented on src/main/java/emissary/util/DataUtil.java
> +     * Return true if the data is empty or consists only of blank space or control characters
```suggestion
     * Return true if the data is null or empty
```

2024-04-02 15:21 UTC, drivenflywheel commented on src/main/java/emissary/util/DataUtil.java
> +     * Return true if the data slot is empty or just one blank space character
```suggestion
     * Return true if the data slot is empty
```

2024-04-05 14:36 UTC, sambish5 approved these changes

2024-04-05 16:22 UTC, drivenflywheel approved these changes

2024-04-05 16:24 UTC, merged