adding ability to pull from different directories for test data & answer files
NationalSecurityAgency/emissary pull request #783
Opened 2024-05-20 13:17 UTC by sambish5

creates getMyTestAnswerFiles, which allows for test answer files from one directory to work with data files from another directory.

2024-05-20 14:49 UTC, dev-mlb commented on src/test/java/emissary/test/core/junit5/UnitTest.java
> +            int testFileName = resource.lastIndexOf("/");
```suggestion
           String testFileName = FilenameUtils.getBaseName(resource);
```

2024-05-20 14:52 UTC, dev-mlb requested changes

2024-05-20 14:52 UTC, dev-mlb commented on src/test/java/emissary/test/core/junit5/UnitTest.java
> +                if (answer.contains(resource.substring(testFileName + 1, datPos))) {
```suggestion
                if (FilenameUtils.getBaseName(answer).equals(testFileName)) {
```

2024-05-20 14:52 UTC, dev-mlb commented on src/test/java/emissary/test/core/junit5/UnitTest.java
> +            int testFileName = resource.lastIndexOf("/");
```suggestion
            String testFileName = FilenameUtils.getBaseName(resource);
```

2024-05-20 14:52 UTC, dev-mlb commented on src/test/java/emissary/test/core/junit5/UnitTest.java
> +    public static Stream<? extends Arguments> getMyTestAnswerFiles(Class<?> answerClass, Class<?> dataClass) {
Maybe something more like this?? --
```
    public static Stream<? extends Arguments> getMyTestParameterFiles(Class<?> clz) {
        return getMyTestParameterFiles(clz, clz);
    }

    public static Stream<? extends Arguments> getMyTestParameterFiles(Class<?> clz, Class<?> ansClz) {
        ResourceReader rr = new ResourceReader();
        List<String> rs = rr.findDataResourcesFor(clz);
        answerFiles = getMyTestAnswerFiles(rr, ansClz);
        return rs.stream().map(Arguments::of);
    }

    private static List<String> getMyTestAnswerFiles(ResourceReader rr, Class<?> answerClass) {
        return rr.findXmlResourcesFor(answerClass);
    }
```

2024-05-21 12:53 UTC, dev-mlb approved these changes

2024-05-21 18:14 UTC, fbruton requested changes

2024-05-21 18:14 UTC, fbruton commented on src/test/java/emissary/test/core/junit5/UnitTest.java
> +                    aname = answer;
Suggest we break out after finding a match.
```suggestion
                    aname = answer;
                    break;
```

2024-05-23 12:13 UTC, jpdahlke approved these changes

2024-05-23 12:15 UTC, fbruton approved these changes

2024-05-23 12:34 UTC, merged