refactor CoordinationPlace to improve extensibility and reduce complexity
NationalSecurityAgency/emissary pull request #877
Opened 2024-08-06 02:24 UTC by fbruton

…xity

2024-08-06 09:27 UTC, cfkoehler submitted a review, later dismissed
Just one spelling mistake that was copied over. Otherwise I did not find any functional differences which is expected/

2024-08-06 09:27 UTC, cfkoehler commented on src/main/java/emissary/place/CoordinationPlace.java
> +        // Process the ouptut form according to configuration
```suggestion
        // Process the output form according to configuration
```

2024-08-06 11:27 UTC, cfkoehler submitted a review, later dismissed

2024-08-06 12:10 UTC, jpdahlke commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean allowShouldNotContinueOnError() {
```suggestion
    protected boolean shouldNotContinueOnError() {
```

2024-08-06 12:19 UTC, jpdahlke commented on src/main/java/emissary/place/CoordinationPlace.java
> +    private boolean shouldNotContinueOnError(IServiceProviderPlace p, boolean errorOccurred) {
I think the logic here should be reversed; `shouldContinueOnErrror` will return a "false" on "continue" rather than "true" on a "not continue".

2024-08-06 12:30 UTC, jpdahlke commented on src/main/java/emissary/place/CoordinationPlace.java
> +        if (allowShouldNotContinueOnError() && errorOccurred) {
I'm not sure this has to exist as part of the override. I could see wanting to override the private method in this case to do something other than the default scenario. 

`protected boolean shouldContinue(p, errorOccurred)`

`protected boolean continueOnError()`

2024-08-06 14:13 UTC, drivenflywheel reviewed
Minor naming suggestions, but nothing I feel strongly about.  I like the direction this is going.

2024-08-06 14:13 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean handlePlaceException(boolean hd, Exception ex) {
If this method will have a boolean return value, its name should reflect probably that.  Something like `handledPlaceException` or `placeExceptionWasHandled`.  

Should we consider passing a reference to the place that threw the exception? (i.e., adding another parameter)

2024-08-06 14:13 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +        logger.warn("agentProcess {} called from Coordinate problem", (hd ? "HeavyDuty" : "Call"), ex);
Should lose the extra space here that's breaking up the called method name:
```suggestion
        logger.warn("agentProcess{} called from Coordinate problem", (hd ? "HeavyDuty" : "Call"), ex);
```

2024-08-06 14:13 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected void processOutputForm(IBaseDataObject d) {
Maybe `applyOutputForm` describes the functionality more specifically than `processOutputForm` does?

2024-08-06 14:13 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean allowProcessOutputFormOnError() {
Maybe?
```suggestion
    protected boolean shouldApplyOutputFormOnError() {
```

2024-08-06 14:13 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +        if (allowProcessOutputFormOnError() || !errorOccurred) {
Should probably swap the order of these so we can short-circuit on a boolean value without having to evaluate the method call
```suggestion
        if (!errorOccurred || allowProcessOutputFormOnError())  {
```

2024-08-07 13:29 UTC, cfkoehler approved these changes

2024-08-07 19:30 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean shouldContinue(IServiceProviderPlace p, boolean errorOccurred) {
Let's move this new overload to be adjacent to the existing `shouldContinue` method

2024-08-07 19:32 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean shouldApplyOutputFormOnError() {
(optional) Could we move this just before the other `shouldXXX` methods?

2024-08-07 19:37 UTC, drivenflywheel commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean shouldApplyOutputFormOnError() {
Scratch that - this is already close to where it's used so the cohesion is still pretty good

2024-08-07 19:42 UTC, jpdahlke requested changes
minor comments

2024-08-07 19:42 UTC, jpdahlke commented on src/main/java/emissary/place/CoordinationPlace.java
> +    protected boolean handledPlaceException(IServiceProviderPlace p, boolean hd, Exception ex) {
```suggestion
    protected boolean handlePlaceException(IServiceProviderPlace p, boolean hd, Exception ex) {
```

2024-08-07 19:42 UTC, jpdahlke commented on src/main/java/emissary/place/CoordinationPlace.java
> +     * Return false when an error has occurred and the places is configured to not continue
```suggestion
     * Return whether to continue traversing the list of coordinated places when an error occurs in one of them
```

2024-08-07 19:42 UTC, jpdahlke commented on src/main/java/emissary/place/CoordinationPlace.java
> +     * Apply the form
```suggestion
     * How to handle applying the output form if an error occurred during processing
```

2024-08-07 19:58 UTC, drivenflywheel approved these changes

2024-08-07 20:36 UTC, cfkoehler approved these changes

2024-08-07 21:03 UTC, jpdahlke approved these changes

2024-08-07 21:04 UTC, merged