Adding support to link a tld to a child IBDO for inheriting parameters
NationalSecurityAgency/emissary pull request #919
Opened 2024-09-09 22:58 UTC by rpg36

An effort to link children to the top level document to inherit their metadata instead of copying it down.

2024-09-11 00:18 UTC, fbruton requested changes

2024-09-11 00:18 UTC, fbruton commented on src/main/java/emissary/core/BaseDataObject.java
> +    protected final Set<String> inheritedKeys;
Recommend removing this field from the BaseDataObject` and passing as a parameter to `IBaseDataObjectHelper#getParametersWithInheritance()`

2024-09-11 00:18 UTC, fbruton commented on src/main/java/emissary/core/BaseDataObject.java
> +    protected final IBaseDataObject parent;
I agree with @drivenflywheel. Parent and TLD have different meanings when the BaseDataObject is more than one level down in the hierarchy.

2024-09-11 00:25 UTC, fbruton commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +    public static Map<String, Collection<Object>> getParametersWithInheritance(IBaseDataObject payload) {
```suggestion
    public static Map<String, Collection<Object>> getCombinedTldParameters(IBaseDataObject payload) {
```

2024-09-11 00:30 UTC, fbruton commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +                if (inheritedParameters == null || inheritedParameters.contains(key)) {
Only add the TLD parameter if current `BaseDataObject` parameter's doesn't contain the key.

2024-09-11 18:39 UTC, fbruton commented on src/main/java/emissary/core/IBaseDataObjectHelper.java
> +                if (inheritedParameters == null || inheritedParameters.contains(key)) {
See LogFilter.java

2024-09-11 20:33 UTC, rpg36 commented on src/main/java/emissary/core/BaseDataObject.java
> +    protected final IBaseDataObject parent;
Naming conventions updated.

2024-09-12 11:02 UTC, fbruton requested changes

2024-10-25 13:44 UTC, dev-mlb commented on src/main/java/emissary/core/BaseDataObject.java
> +        setData(newData);
Any reason not to use `this(newData, name, form);`? Do you not want the creation timestamp set??

2024-11-25 16:15 UTC, closed without merging