Made AbstractFilter Denylist settings configurable
NationalSecurityAgency/emissary pull request #925
Opened 2024-09-12 16:48 UTC by rupert-griffin

Can now configure the allowed characters in a denylist entry. Use Regex format. e.g. `ALLOWED_NAME_CHARS= "a-zA-Z0-9_"`

Allowed characters will get substituted into the patterns for view name formatting and character ordering. These regexes can also be configured differently, either using `%s` to substitute the allowed character string, or manually typing out the allowed chars.

2024-09-13 14:20 UTC, fbruton requested changes
Please add a unit-test that exercises the regular expressions.

2024-09-13 16:26 UTC, fbruton submitted a review, later dismissed

2024-09-16 20:18 UTC, cfkoehler approved these changes

2024-09-17 00:16 UTC, fbruton approved these changes

2024-09-17 01:49 UTC, merged