updates to VersionPlace for less code-reusage downstream
NationalSecurityAgency/emissary pull request #952
Opened 2024-09-25 13:22 UTC by sambish5

Basically gets rid of the use of `emissary.util.Version`, and relies on `GitRepositoryState` to get the version and hash. This allows for a lot less code-reusage for classes downstream that extend this.
Created setters for the booleans so they can be set downstream.

One thing to keep in mind for this is the time is only reset in the `emissary.git.properties` file when "mvn clean" is run

2024-09-25 18:42 UTC, dev-mlb requested changes

2024-09-25 18:42 UTC, dev-mlb commented on src/main/java/emissary/place/VersionPlace.java
> +    public void setIncludeDate(Boolean includeDate) {
add getters

2024-09-26 13:40 UTC, sambish5 commented on src/main/java/emissary/place/VersionPlace.java
> +    public void setIncludeDate(Boolean includeDate) {
added them in

2024-09-30 19:56 UTC, dev-mlb approved these changes

2024-10-18 17:11 UTC, jpdahlke approved these changes

2024-10-18 17:11 UTC, merged