Adding listIndexOf method to KeywordScanner
NationalSecurityAgency/emissary pull request #966
Opened 2024-10-09 15:51 UTC by nixon124

Adding the ability to search for occurrences of a pattern and return a list of positions in which the pattern starts.

2024-10-21 16:18 UTC, fbruton commented on src/main/java/emissary/util/search/ByteMatcher.java
> +            return EMPTYLIST;
Update other occurrences as well.
```suggestion
    public List<Integer> indexListIgnoreCase(byte[] pattern, int beginIndex, int endIndex) {

        // Impossible to find under these conditions
        if (mydata == null || beginIndex > (mydata.length - pattern.length) || endIndex > mydata.length) {
            return Collections.emptyList();
```

2024-10-21 16:18 UTC, fbruton commented on src/main/java/emissary/util/search/ByteMatcher.java
> +    public static final ArrayList<Integer> EMPTYLIST = new ArrayList<>();
```suggestion
```

2024-10-21 16:37 UTC, drivenflywheel requested changes

2024-10-21 16:37 UTC, drivenflywheel commented on src/main/java/emissary/util/search/ByteMatcher.java
Within this file and in KeywordScanner.java, let's move the new `listIndexOf` overloads to be consecutive, and after all the 'indexOf` overloads.  (i.e., don't break up the `indexOf` overloads by mirroring their order.) 

Same thing for the new `indexListIgnoreCase` methods in this file

2024-10-21 16:37 UTC, drivenflywheel commented on src/main/java/emissary/util/search/ByteMatcher.java
In this class and in `KeywordScanner`, let's change the return type of the new methods from `ArrayList<Integer>` to `List<Integer>`

2024-10-21 16:37 UTC, drivenflywheel commented on src/test/java/emissary/util/search/ByteMatcherTest.java
> +        Collections.addAll(findTestCaseSensitive, 10, 26, 47);
```suggestion
        List<Integer> findTestCaseSensitive = List.of(10, 26, 47);
```

2024-10-21 16:37 UTC, drivenflywheel commented on src/test/java/emissary/util/search/ByteMatcherTest.java
> +        Collections.addAll(findTestCaseInsensitive, 10, 26, 47, 53);
```suggestion
        List<Integer> findTestCaseInsensitive = List.of(10, 26, 47, 53);
```

2024-10-21 16:37 UTC, drivenflywheel commented on src/test/java/emissary/util/search/ByteMatcherTest.java
> +        String stop = "Stop";
```suggestion
```

2024-10-21 16:37 UTC, drivenflywheel commented on src/test/java/emissary/util/search/KeywordScannerTest.java
> +    private KeywordScanner lks;
Make this a private variable in the `testListIndexOf` method

2024-10-21 16:37 UTC, drivenflywheel commented on src/test/java/emissary/util/search/KeywordScannerTest.java
> +        Collections.addAll(findTest, 10, 26, 47);
```suggestion
        List<Integer> findTest = List.of(10, 26, 47);
```

2024-10-21 16:37 UTC, drivenflywheel commented on src/test/java/emissary/util/search/KeywordScannerTest.java
> +        Collections.addAll(findIs, 2, 5, 21, 39, 42);
```suggestion
        List<Integer> findIs = List.of(2, 5, 21, 39, 42);
```

2024-10-21 17:55 UTC, drivenflywheel approved these changes

2024-10-22 15:04 UTC, ldhardy approved these changes

2024-10-22 16:55 UTC, merged